coverage:
  precision: 2
  round: down
  range: "60...80"
  
  status:
    project:
      default:
        target: 60%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "tests/*"
  - "docs/*"
  - "tools/*"
  - "**/__pycache__"
  - "**/*.pyc" 