# TODO: add comments

# ---------------------------------------------------------------------------
# PROBLEM params
# ---------------------------------------------------------------------------

# Vehicle Types and Capacities
vehicles:
  A_Dry: # SCV - Carries all goods by default
    capacity: 2000
    fixed_cost: 100
    avg_speed: 30  # km/h
    service_time: 25  # minutes per customer
    max_route_time: 10  # hours
    allowed_goods:
      - Dry
  A_Chilled: # SCV - Carries all goods by default
    capacity: 2000
    fixed_cost: 100
    avg_speed: 30  # km/h
    service_time: 25  # minutes per customer
    max_route_time: 10  # hours
    allowed_goods:
      - Chilled
  A_Frozen: # SCV - Carries all goods by default  
    capacity: 2000
    fixed_cost: 100
    avg_speed: 30  # km/h
    service_time: 25  # minutes per customer
    max_route_time: 10  # hours
    allowed_goods:
      - Frozen

# Cost Parameters
variable_cost_per_hour: 10.00

# Location
depot:
  latitude: 4.7
  longitude: -74.1

# Product Types
goods:
  - Dry
  - Chilled
  - Frozen

# Math model Parameters
light_load_penalty: 0  # Adjust penalty value as needed -- 0 == don't penalize
light_load_threshold: 0  # Threshold for light load (e.g., 0.2 for 20%) -- when to penalize
compartment_setup_cost: 10  # Cost per additional compartment beyond the first one

# Split-stop capability
allow_split_stops: true  # Allow customers to be served by multiple vehicles

# ---------------------------------------------------------------------------
# ALGORITHM params
# ---------------------------------------------------------------------------

# Clustering Parameters
clustering:
  max_depth: 20
  method: combine  # Options: minibatch_kmeans, kmedoids, agglomerative, combine
  distance: euclidean  # Options: euclidean, composite (only for agglomerative)
  geo_weight: 0.7    # Weight for geographical distance (composite-only)
  demand_weight: 0.3  # Weight for demand distance (composite-only)
  route_time_estimation: 'BHH'  # Options: TSP, BHH, Legacy

prune_tsp: false  # Skip TSP based on BHH estimate

# Post-optimization
post_optimization: true         # Enable iterative improvement phase
small_cluster_size: 1000         # ≤ customers per "small" cluster
nearest_merge_candidates: 1000   # max neighbour clusters to probe
max_improvement_iterations: 20  # max iterations for iterative post-optimization

# Merge phase pre-MILP
pre_small_cluster_size: 5
pre_nearest_merge_candidates: 50

# ---------------------------------------------------------------------------
# IO params
# ---------------------------------------------------------------------------

# Data Files
# See options in data/demand_profiles/
demand_file: "sales_2024_avg_day_demand.csv"

# Output format
format: 'json'  # Output format (excel or json)

# ---------------------------------------------------------------------------
# RUNTIME params
# ---------------------------------------------------------------------------

# TODO: add solver parameters
verbose: true      # Enable verbose output
debug: false        # Enable debug mode 
# TODO: check debug-milp mode
solver: gurobi        # auto | gurobi | cbc
gap_rel: 0.0        # relative MIP gap
time_limit: 60     # seconds; None = no limit
