# Available Fleet
vehicles:
  A:
    capacity: 2700
    fixed_cost: 100
    avg_speed: 30.0
    service_time: 25.0
    max_route_time: 10.0
  B:
    capacity: 3300
    fixed_cost: 175
    avg_speed: 30.0
    service_time: 25.0
    max_route_time: 10.0
  C:
    capacity: 4500
    fixed_cost: 225
    avg_speed: 30.0
    service_time: 25.0
    max_route_time: 10.0

variable_cost_per_hour: 10.0
depot:
  latitude: 4.7
  longitude: -74.1
goods:
- Dry
- Chilled
- Frozen

clustering:
  max_depth: 20
  method: combine
  distance: euclidean
  geo_weight: 0.7
  demand_weight: 0.3
  route_time_estimation: BHH
prune_tsp: false
demand_file: sales_2024_avg_day_demand.csv
light_load_penalty: 0
light_load_threshold: 0
compartment_setup_cost: 0
post_optimization: true
small_cluster_size: 1000
nearest_merge_candidates: 1000
max_improvement_iterations: 100
format: excel
