# Example configuration demonstrating vehicle-specific goods capability
# This shows how to configure a mixed fleet with specialized vehicles

vehicles:
  # Standard dry goods truck - can only carry dry products
  DryTruck:
    capacity: 2700
    fixed_cost: 100
    avg_speed: 30
    service_time: 25
    max_route_time: 10
    allowed_goods: ["Dry"]
  
  # Refrigerated truck - can carry chilled and frozen but not dry
  RefrigeratedTruck:
    capacity: 3300
    fixed_cost: 175
    avg_speed: 30
    service_time: 25
    max_route_time: 10
    allowed_goods: ["Chilled", "Frozen"]
  
  # Multi-temperature truck - can carry all goods (no allowed_goods specified)
  MultiTempTruck:
    capacity: 4500
    fixed_cost: 225
    avg_speed: 30
    service_time: 25
    max_route_time: 10
    # No allowed_goods specified - can carry all goods
  
  # Frozen specialist - high capacity but only for frozen goods
  FrozenSpecialist:
    capacity: 5000
    fixed_cost: 250
    avg_speed: 30
    service_time: 25
    max_route_time: 10
    allowed_goods: ["Frozen"]

# Global goods list - all possible product types
goods:
  - Dry
  - Chilled
  - Frozen

# Depot location
depot:
  latitude: 40.7128
  longitude: -74.0060

# Clustering parameters
clustering:
  method: minibatch_kmeans
  max_depth: 3
  route_time_estimation: TSP
  geo_weight: 0.7
  demand_weight: 0.3

# Other optimization parameters
demand_file: demand.csv
variable_cost_per_hour: 50
light_load_penalty: 50
light_load_threshold: 0.5
compartment_setup_cost: 10
format: csv
post_optimization: true

# Benefits of this configuration:
# 1. DryTruck: Lower cost for dry-only deliveries
# 2. RefrigeratedTruck: Specialized for cold chain without dry goods capability
# 3. MultiTempTruck: Flexible but more expensive, good for mixed deliveries
# 4. FrozenSpecialist: High capacity for frozen-only routes

# The optimization will automatically:
# - Assign dry-only customers to DryTruck when beneficial
# - Use RefrigeratedTruck for chilled/frozen only deliveries
# - Deploy MultiTempTruck for customers needing all three goods
# - Utilize FrozenSpecialist for large frozen-only demands 