# Example FleetMix Configuration with Allowed Goods Feature
# This demonstrates how to configure specialized vehicles for different goods types

# Vehicle specifications with allowed goods restrictions
vehicles:
  # Standard dry van - can only carry dry goods
  DryVan:
    capacity: 1500
    fixed_cost: 100
    avg_speed: 35
    service_time: 20
    max_route_time: 10
    allowed_goods: ["Dry"]  # Restricted to dry goods only
  
  # Refrigerated truck - can carry chilled and frozen goods
  RefrigeratedTruck:
    capacity: 1200
    fixed_cost: 250
    avg_speed: 30
    service_time: 25
    max_route_time: 8
    allowed_goods: ["Chilled", "Frozen"]  # Cold chain goods only
  
  # Multi-temperature truck - can carry all goods (most expensive)
  MultiTempTruck:
    capacity: 2000
    fixed_cost: 400
    avg_speed: 28
    service_time: 30
    max_route_time: 9
    # No allowed_goods specified = can carry all goods

# Goods types
goods: ["Dry", "Chilled", "Frozen"]

# Depot location (New York City)
depot:
  latitude: 40.7128
  longitude: -74.0060

# Cost parameters
variable_cost_per_hour: 50
light_load_penalty: 100
light_load_threshold: 0.3
compartment_setup_cost: 25

# Clustering configuration
clustering:
  method: combine
  max_depth: 20
  route_time_estimation: BHH
  geo_weight: 0.7
  demand_weight: 0.3

# Optimization settings
post_optimization: true
small_cluster_size: 3
nearest_merge_candidates: 10
max_improvement_iterations: 5
prune_tsp: true

# Output format
format: excel

# Benefits of this configuration:
# 1. DryVan: Lower cost for dry-only deliveries
# 2. RefrigeratedTruck: Specialized for cold chain without dry goods capability
# 3. MultiTempTruck: Flexible but more expensive, good for mixed deliveries
# 4. FrozenSpecialist: High capacity for frozen-only routes

# The optimization will automatically:
# - Assign dry-only customers to DryVan when beneficial
# - Use RefrigeratedTruck for chilled/frozen only deliveries
# - Deploy MultiTempTruck for customers needing all three goods
# - Utilize FrozenSpecialist for large frozen-only demands 